version: '3'
services:
    postgres:
        image: postgres:18.3
        environment:
            POSTGRES_DB: chat_buddy
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 567234
        ports:
            - '5432:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql
